CREATE TABLE alzheimer_features (
    feature_id INT AUTO_INCREMENT PRIMARY KEY,
    patient_id INT,
    CDRSB FLOAT,
    mPACCdigit FLOAT,
    MMSE FLOAT,
    LDELTOTAL FLOAT,
    mPACCtrailsB FLOAT,
    EcogSPPlan FLOAT,
    RAVLT_immediate FLOAT,
    FAQ FLOAT,
    EcogPtTotal FLOAT,
    Entorhinal FLOAT,
    PTEDUCAT FLOAT,
    Ventricles FLOAT,
    Fusiform FLOAT,
    EcogSPOrgan FLOAT,
    APOE4 FLOAT,
    EcogPtLang FLOAT,
    FDG FLOAT,
    MidTemp FLOAT,
    TRABSCOR FLOAT,
    EcogSPDivatt FLOAT,
    ADAS11 FLOAT,
    EcogPtVisspat FLOAT,
    AGE FLOAT,
    ADAS13 FLOAT,
    EcogSPMem FLOAT,
    EcogPtOrgan FLOAT,
    ICV FLOAT,
    Hippocampus FLOAT,
    EcogSPVisspat FLOAT,
    MOCA FLOAT,
    WholeBrain FLOAT,
    PTRACCAT FLOAT,
    RAVLT_learning FLOAT,
    DIGITSCOR FLOAT,
    PTGENDER FLOAT,
    EcogSPTotal FLOAT,
    RAVLT_perc_forgetting FLOAT,
    ABETA FLOAT,
    ADASQ4 FLOAT,
    EcogSPLang FLOAT,
    EcogPtMem FLOAT,
    EcogPtDivatt FLOAT,
    RAVLT_forgetting FLOAT,
    EcogPtPlan FLOAT,
    PTMARRY FLOAT,
    PTETHCAT FLOAT,
    PTAU FLOAT,
    TAU FLOAT,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id)
);
INSERT INTO alzheimer_features (
    patient_id, CDRSB, mPACCdigit, MMSE, LDELTOTAL, mPACCtrailsB, EcogSPPlan, RAVLT_immediate,
    FAQ, EcogPtTotal, Entorhinal, PTEDUCAT, Ventricles, Fusiform, EcogSPOrgan, APOE4,
    EcogPtLang, FDG, MidTemp, TRABSCOR, EcogSPDivatt, ADAS11, EcogPtVisspat, AGE, ADAS13,
    EcogSPMem, EcogPtOrgan, ICV, Hippocampus, EcogSPVisspat, MOCA, WholeBrain, PTRACCAT,
    RAVLT_learning, DIGITSCOR, PTGENDER, EcogSPTotal, RAVLT_perc_forgetting, ABETA, ADASQ4,
    EcogSPLang, EcogPtMem, EcogPtDivatt, RAVLT_forgetting, EcogPtPlan, PTMARRY, PTETHCAT,
    PTAU, TAU
) VALUES (
    1, 2.0, 5.3, 25.0, 10.2, 8.7, 1.5, 20.0,
    4.0, 10.0, 3500.0, 16.0, 15000.0, 2300.0, 2.0, 1.0,
    2.5, 120.0, 4000.0, 35.0, 3.2, 25.0, 2.8, 73.0, 30.5,
    4.5, 3.1, 1400.0, 2800.0, 3.0, 23.0, 1150000.0, 1.0,
    7.0, 8.0, 1.0, 18.0, 0.25, 800.0, 3.0,
    2.5, 3.5, 1.2, 0.7, 1.0, 1.0, 2.0,
    85.0, 500.0
);
